name: quiar
description: QUIC impl by pure dart
version: 0.0.0
repository: https://github.com/hellok-rc/quiar

environment:
  sdk: ^3.10.7

dependencies:
  freezed_annotation: ^3.1.0
  cryptography: ^2.9.0
  equatable: ^2.0.8

dev_dependencies:
  # lints: ^6.0.0
  # test: ^1.25.6
  benchmark_harness: ^2.4.0
  build_runner: ^2.10.5
  freezed: ^3.2.4